default_language_version:
  python: python3
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: test
        name: Run tests
        entry: tox
        language: system
        types: [ python ]
        stages: [ push ]

      - id: update-reqs
        name: Update requirements.txt
        entry: ./misc/update_reqs.sh
        language: system
        stages: [ push ]

      - id: check-versions
        name: Check project versions
        entry: python ./misc/check_versions.py
        language: system
        stages: [ commit ]