[tool.poetry]
name = "snp_pred"
version = "0.1.0"
description = ""
authors = ["Arnor Sigurdsson"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.3"
numpy = "^1.19.2"
torch = "^1.7.0"
torchvision = "^0.8.1"
py = "^1.9.0"
matplotlib = "^3.3.2"
pytorch-ignite = "^0.4.2"
tqdm = "^4.50.2"
sympy = "^1.6.2"
scikit-learn = "^0.23.2"
shap = "^0.37.0"
seaborn = "^0.11.0"
joblib = "^0.17.0"
tensorboard = "^2.3.0"
ConfigArgParse = "^1.2.3"
plotly = "^4.11.0"
aislib = {git = "ssh://git@github.com/arnor-sigurdsson/aislib.git", rev = "dev"}
torch-optimizer = "^0.0.1-alpha.15"
black = "^20.8b1"
adabelief-pytorch = "^0.1.0"
dill = "^0.3.3"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
tox = "^3.20.1"
flake8 = "^3.8.4"
jupyter = "^1.0.0"
ipykernel = "^5.3.4"
Sphinx = "^3.2.1"
coverage = "^5.3"
snakeviz = "^2.1.0"
pytest-cov = "^2.10.1"
pytest-testmon = "^1.0.3"
pynvim = "^0.4.2"
visidata = "^2.0.1"
pre-commit = "^2.7.1"
gpustat = "^0.6.0"
pyinstaller = "^4.0"
hypothesis = "^5.37.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
