name: Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - name: Run tests
      run: |
        pip install tox==4.5.1
        pip install poetry==1.4.2
        tox -e py
    - name: Generate report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true

