name: Coverage
on: [push, pull_request]
jobs:

  coverage:
    name: Coverage
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Run tests
      run: |
        pip install tox==3.28.0
        pip install poetry==1.3.1
        tox -e py310
    - name: Generate report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true

