name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  getrelease:
    name: Get release
    runs-on: ubuntu-20.04
    outputs:
      versionoutput: ${{ steps.getversiontag.outputs.VERSION }}
    steps:
      - name: Get the tag version
        id: getversiontag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


  build:
    name: Build packages
    needs: getrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:

          - os: ubuntu-20.04
            TARGET: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true

  upload:
    name: Upload to PyPI
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - run: pip install poetry==1.1.7
      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}

