name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}
        run: |
          pip install tox==4.6.4
          pip install poetry==1.5.1
          tox -e py

  getrelease:
    name: Get release
    needs: test
    runs-on: ubuntu-22.04
    outputs:
      versionoutput: ${{ steps.getversiontag.outputs.VERSION }}
    steps:
      - name: Get the tag version
        id: getversiontag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


  build:
    name: Build packages
    needs: getrelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:

          - os: ubuntu-22.04
            TARGET: ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true

  upload:
    name: Upload to PyPI
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: x64
      - run: pip install poetry==1.5.1
      - run: poetry build
      - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}

