name: Test
on: [push, pull_request]
jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests with Python ${{ matrix.python-version }} on ${{ matrix.os }}
        run: |
          pip install tox==3.28.0
          pip install poetry==1.3.1
          tox -e py